### ISSUE TITLE
"Error: Can’t find package.json for `fs`" while testing with mocha

### ISSUE THREAD

**Issue by silvestreh** [dfcreative/require-stub#2]
I'm getting this (rather strange) error while trying to run tests through `mocha-phantomjs`

``` shell
Error: Can’t find package.json for `fs`. in http://localhost:8080/node_modules/source-map-support/source-map-support.js

   in require at http://localhost:8080/node_modules/require-stub/index.js:162
   at :485
   at :3
   at :485
```

I resorted to installing a dummy `fs` module from `npm`, but I doubt this is the way to go as `fs` is a core Node module.

**Comment by silvestreh** [comment]
Interesting fact… I'm not using the `fs` module at all.

**Comment by dy** [comment]
Hi! I would strongly encourage you to switch to [budo](http://npmjs.org/package/budo). That is faster and simpler, and do not cause such errors.

**Comment by silvestreh** [comment]
Alright, I'll take a look. Thanks!
